/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as WorkspacesWorkspaceIdAppsAppIdRouteImport } from './routes/workspaces_.$workspaceId.apps.$appId'
import { Route as ApiAppsAppIdProcessStreamRouteImport } from './routes/api.apps.$appId.process-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdAppsAppIdRoute =
  WorkspacesWorkspaceIdAppsAppIdRouteImport.update({
    id: '/workspaces_/$workspaceId/apps/$appId',
    path: '/workspaces/$workspaceId/apps/$appId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppsAppIdProcessStreamRoute =
  ApiAppsAppIdProcessStreamRouteImport.update({
    id: '/api/apps/$appId/process-stream',
    path: '/api/apps/$appId/process-stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/api/apps/$appId/process-stream': typeof ApiAppsAppIdProcessStreamRoute
  '/workspaces/$workspaceId/apps/$appId': typeof WorkspacesWorkspaceIdAppsAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/api/apps/$appId/process-stream': typeof ApiAppsAppIdProcessStreamRoute
  '/workspaces/$workspaceId/apps/$appId': typeof WorkspacesWorkspaceIdAppsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/api/apps/$appId/process-stream': typeof ApiAppsAppIdProcessStreamRoute
  '/workspaces_/$workspaceId/apps/$appId': typeof WorkspacesWorkspaceIdAppsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspaces/$workspaceId'
    | '/api/apps/$appId/process-stream'
    | '/workspaces/$workspaceId/apps/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspaces/$workspaceId'
    | '/api/apps/$appId/process-stream'
    | '/workspaces/$workspaceId/apps/$appId'
  id:
    | '__root__'
    | '/'
    | '/workspaces/$workspaceId'
    | '/api/apps/$appId/process-stream'
    | '/workspaces_/$workspaceId/apps/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  ApiAppsAppIdProcessStreamRoute: typeof ApiAppsAppIdProcessStreamRoute
  WorkspacesWorkspaceIdAppsAppIdRoute: typeof WorkspacesWorkspaceIdAppsAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId/apps/$appId': {
      id: '/workspaces_/$workspaceId/apps/$appId'
      path: '/workspaces/$workspaceId/apps/$appId'
      fullPath: '/workspaces/$workspaceId/apps/$appId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdAppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps/$appId/process-stream': {
      id: '/api/apps/$appId/process-stream'
      path: '/api/apps/$appId/process-stream'
      fullPath: '/api/apps/$appId/process-stream'
      preLoaderRoute: typeof ApiAppsAppIdProcessStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  ApiAppsAppIdProcessStreamRoute: ApiAppsAppIdProcessStreamRoute,
  WorkspacesWorkspaceIdAppsAppIdRoute: WorkspacesWorkspaceIdAppsAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
